//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiparisDetay
    {
        public int siparisDetayUrunId { get; set; }
        public int siparisDetayId { get; set; }
        public int siparisDetayAdetId { get; set; }
    
        public virtual Siparisler Siparisler { get; set; }
        public virtual Urun Urun { get; set; }
    }
}
