//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uyg03.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun
    {
        public int urunId { get; set; }
        public string urunAdi { get; set; }
        public int urunKatId { get; set; }
        public decimal urunFiyat { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual SiparisDetay SiparisDetay { get; set; }
    }
}
